//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string UrlString { get; set; }
        public string IconUrl { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool Del_Flag { get; set; }
    }
}
